<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">

<HTML>
<HEAD>
	
	<META HTTP-EQUIV="CONTENT-TYPE" CONTENT="text/html; charset=iso-8859-1">
	<TITLE>Jarntimarra Itinerary</TITLE>
	<META NAME="GENERATOR" CONTENT="StarOffice/5.2 (Linux)">
	<META NAME="CREATED" CONTENT="20011025;16443900">
	<META NAME="CHANGED" CONTENT="16010101;0">
	
</HEAD>

<STYLE>
	<!-- 
	BODY { font-family: "Helvetica"; font-size: 2 }
	 -->
</STYLE>

<BODY TEXT="#000000" BGCOLOR="#ffffff">
<HR>
	<P><CENTER>
		<H1>Jarntimarra Itinerary</H1>
		<A HREF="#table0">Itinerary</A><BR>
		<A HREF="#table1">Team</A><BR>
		
	</CENTER></P>
<HR>
<A NAME="table0"><H1>Sheet 1: <EM>Itinerary</EM></H1></A>
<TABLE FRAME=VOID CELLSPACING=0 COLS=15 RULES=GROUPS BORDER=1>
	<COLGROUP><COL WIDTH=154><COL WIDTH=107><COL WIDTH=107><COL WIDTH=107><COL WIDTH=107><COL WIDTH=107><COL WIDTH=107><COL WIDTH=107><COL WIDTH=107><COL WIDTH=107><COL WIDTH=107><COL WIDTH=107><COL WIDTH=107><COL WIDTH=107><COL WIDTH=107></COLGROUP>
	<TBODY>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><FONT FACE="Arial">Sat</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><FONT FACE="Arial">Sun</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><FONT FACE="Arial">Mon</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><FONT FACE="Arial">Tue</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><FONT FACE="Arial">Wed</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><FONT FACE="Arial">Thu</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><FONT FACE="Arial">Fri</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><FONT FACE="Arial">Sat</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><FONT FACE="Arial">Sun</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><FONT FACE="Arial">Mon</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><FONT FACE="Arial">Tue</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><FONT FACE="Arial">Wed</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><FONT FACE="Arial">Thu</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><FONT FACE="Arial">Fri</FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="37191" SDNUM="1033;0;DD. MMM YY"><FONT FACE="Arial">27. Oct 01</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="37192" SDNUM="1033;0;DD. MMM YY"><FONT FACE="Arial">28. Oct 01</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="37193" SDNUM="1033;0;DD. MMM YY"><FONT FACE="Arial">29. Oct 01</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="37194" SDNUM="1033;0;DD. MMM YY"><FONT FACE="Arial">30. Oct 01</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="37195" SDNUM="1033;0;DD. MMM YY"><FONT FACE="Arial">31. Oct 01</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="37196" SDNUM="1033;0;DD. MMM YY"><FONT FACE="Arial">01. Nov 01</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="37197" SDNUM="1033;0;DD. MMM YY"><FONT FACE="Arial">02. Nov 01</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="37198" SDNUM="1033;0;DD. MMM YY"><FONT FACE="Arial">03. Nov 01</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="37199" SDNUM="1033;0;DD. MMM YY"><FONT FACE="Arial">04. Nov 01</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="37200" SDNUM="1033;0;DD. MMM YY"><FONT FACE="Arial">05. Nov 01</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="37201" SDNUM="1033;0;DD. MMM YY"><FONT FACE="Arial">06. Nov 01</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="37202" SDNUM="1033;0;DD. MMM YY"><FONT FACE="Arial">07. Nov 01</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="37203" SDNUM="1033;0;DD. MMM YY"><FONT FACE="Arial">08. Nov 01</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="37204" SDNUM="1033;0;DD. MMM YY"><FONT FACE="Arial">09. Nov 01</FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM BGCOLOR="#C0C0C0" SDVAL="0.1875" SDNUM="1033;0;H:MM"><FONT FACE="Arial">4:30</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM SDNUM="1033;0;DD. MMM YY"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM SDNUM="1033;0;DD. MMM YY"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM SDNUM="1033;0;DD. MMM YY"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM SDNUM="1033;0;DD. MMM YY"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM SDNUM="1033;0;DD. MMM YY"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM SDNUM="1033;0;DD. MMM YY"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM SDNUM="1033;0;DD. MMM YY"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM SDNUM="1033;0;DD. MMM YY"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM SDNUM="1033;0;DD. MMM YY"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM SDNUM="1033;0;DD. MMM YY"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM SDNUM="1033;0;DD. MMM YY"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#99CC00"><FONT FACE="Arial">Rise</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#99CC00"><FONT FACE="Arial">Rise</FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM BGCOLOR="#C0C0C0" SDVAL="0.208333333333333" SDNUM="1033;0;H:MM"><FONT FACE="Arial">5:00</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#99CC00"><FONT FACE="Arial">Accom</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#99CC00"><FONT FACE="Arial">Accom</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#99CC00"><FONT FACE="Arial">Accom</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#99CC00"><FONT FACE="Arial">Accom</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#99CC00"><FONT FACE="Arial">Accom</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#99CC00"><FONT FACE="Arial">Accom</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#99CC00"><FONT FACE="Arial">Accom</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#99CC00"><FONT FACE="Arial">Accom</FONT></TD>
			<TD ROWSPAN=36 WIDTH=107 HEIGHT=617 ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#FF99CC"><FONT FACE="Arial">Padding</FONT></TD>
			<TD ROWSPAN=21 WIDTH=107 HEIGHT=360 ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#FF99CC"><FONT FACE="Arial">Padding</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial">Breakfast</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial">Breakfast</FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM BGCOLOR="#C0C0C0" SDVAL="0.229166666666667" SDNUM="1033;0;H:MM"><FONT FACE="Arial">5:30</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial">Breakfast</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial">Breakfast</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial">Breakfast</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial">Breakfast</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial">Breakfast</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial">Breakfast</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial">Breakfast</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial">Breakfast</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="0.25" SDNUM="1033;0;H:MM"><FONT FACE="Arial">6:00</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Arkaroola</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#99CC00"><FONT FACE="Arial">Rise</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Arkaroola</FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="0.270833333333333" SDNUM="1033;0;H:MM"><FONT FACE="Arial">6:30</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Woomera</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Arkaringa</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Simpson Desert</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Henbury</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Algebuckiner</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Cooper Creek</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Clifton Hills</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Merty</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Surrounds</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial">Breakfast</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="0.291666666666667" SDNUM="1033;0;H:MM"><FONT FACE="Arial">7:00</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial">Breakfast</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Surrounds</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Sturt Stony</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="0.3125" SDNUM="1033;0;H:MM"><FONT FACE="Arial">7:30</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Oodnadatta</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Desert</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FF9900"><FONT FACE="Arial">Workshop</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="0.333333333333333" SDNUM="1033;0;H:MM"><FONT FACE="Arial">8:00</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#00FFFF"><FONT FACE="Arial">Oodnadatta</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">William Creek</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">and Surrounds</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FF9900"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="0.354166666666666" SDNUM="1033;0;H:MM"><FONT FACE="Arial">8:30</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#00FFFF"><FONT FACE="Arial">Woomera</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Oodnadatta</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FF9900"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="0.375" SDNUM="1033;0;H:MM"><FONT FACE="Arial">9:00</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FF9900"><FONT FACE="Arial">Briefing</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Woomera</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FF9900"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="0.395833333333333" SDNUM="1033;0;H:MM"><FONT FACE="Arial">9:30</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FF9900"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Marla</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial">Freetime</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="0.416666666666666" SDNUM="1033;0;H:MM"><FONT FACE="Arial">10:00</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFFF"><FONT FACE="Arial">Meeting</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Lake Eyre</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Innamincka</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFFF"><FONT FACE="Arial">Meeting</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="0.437499999999999" SDNUM="1033;0;H:MM"><FONT FACE="Arial">10:30</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFFF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#00FFFF"><FONT FACE="Arial">Innamincka</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFFF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="0.458333333333333" SDNUM="1033;0;H:MM"><FONT FACE="Arial">11:00</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Adel</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Lake Eyre</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial">Lunch</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFFF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="0.479166666666666" SDNUM="1033;0;H:MM"><FONT FACE="Arial">11:30</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Alice Springs</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial">Lunch</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial">Lunch</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFFF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Adelaide</FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="0.499999999999999" SDNUM="1033;0;H:MM"><FONT FACE="Arial">12:00</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Lunch</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Dalhousie</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial">Lunch</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Innamincka</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Arkaroola</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial">Lunch</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial">Lunch</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial">Lunch</FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="0.520833333333333" SDNUM="1033;0;H:MM"><FONT FACE="Arial">12:30</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">on road</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Coober Pedy</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial">Lunch</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Oodnadatta</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Lake Eyre</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Sturt Stony</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Surrounds</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#00FFFF"><FONT FACE="Arial">Arkaroola</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="0.541666666666666" SDNUM="1033;0;H:MM"><FONT FACE="Arial">13:00</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial">Lunch</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial">Freetime</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial">Lunch</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Desert</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial">Lunch</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial">Freetime</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial">Freetime</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Adelaide</FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="0.562499999999999" SDNUM="1033;0;H:MM"><FONT FACE="Arial">13:30</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Dalhousie</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">and Surrounds</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Airport</FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="0.583333333333333" SDNUM="1033;0;H:MM"><FONT FACE="Arial">14:00</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#00FFFF"><FONT FACE="Arial">Coober Pedy</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Alice Springs</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Oodnadatta</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Marree</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#99CC00"><FONT FACE="Arial">Accom</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Arkaroola</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial">End of Trip</FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="0.604166666666666" SDNUM="1033;0;H:MM"><FONT FACE="Arial">14:30</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Coober Pedy</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Algebuckiner</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#99CC00"><FONT FACE="Arial">Showers</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#99CC00"><FONT FACE="Arial">(shearer's qtrs)</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Surrounds</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="0.624999999999999" SDNUM="1033;0;H:MM"><FONT FACE="Arial">15:00</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Surrounds</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Henbury</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#99CC00"><FONT FACE="Arial">Accom</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#99CC00"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Merty Merty</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#99CC00"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="0.645833333333333" SDNUM="1033;0;H:MM"><FONT FACE="Arial">15:30</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Woomera</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#99CC00"><FONT FACE="Arial">Accom</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#99CC00"><FONT FACE="Arial">(camp)</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Marree</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Merty Merty</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial">Freetime</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFFF"><FONT FACE="Arial">Meeting</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="0.666666666666666" SDNUM="1033;0;H:MM"><FONT FACE="Arial">16:00</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#99CC00"><FONT FACE="Arial">Accom</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#99CC00"><FONT FACE="Arial">(camp)</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Algebuckiner</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Surrounds</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFFF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FF9900"><FONT FACE="Arial">Workshop</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="0.687499999999999" SDNUM="1033;0;H:MM"><FONT FACE="Arial">16:30</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#99CC00"><FONT FACE="Arial">(caravan park)</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Henbury</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Surrounds</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Mt Painter Tour</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FF9900"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="0.708333333333333" SDNUM="1033;0;H:MM"><FONT FACE="Arial">17:00</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial">Freetime</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Arkaringa</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Simpson Desert</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Surrounds</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Cooper Creek</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FF9900"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="0.729166666666666" SDNUM="1033;0;H:MM"><FONT FACE="Arial">17:30</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#99CC00"><FONT FACE="Arial">Accom</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#99CC00"><FONT FACE="Arial">Accom</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#99CC00"><FONT FACE="Arial">Accom</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial">Clifton Hills</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#99CC00"><FONT FACE="Arial">Accom</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FF9900"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="0.749999999999999" SDNUM="1033;0;H:MM"><FONT FACE="Arial">18:00</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#99CC00"><FONT FACE="Arial">(camp)</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#99CC00"><FONT FACE="Arial">(camp)</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#99CC00"><FONT FACE="Arial">(camp)</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#99CC00"><FONT FACE="Arial">Accom</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#99CC00"><FONT FACE="Arial">(camp)</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FF9900"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM BGCOLOR="#C0C0C0" SDVAL="0.770833333333333" SDNUM="1033;0;H:MM"><FONT FACE="Arial">18:30</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial">Freetime</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial">Freetime</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial">Freetime</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial">Freetime</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#99CC00"><FONT FACE="Arial">(camp)</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial">Dinner</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial">Dinner</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial">Freetime</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM BGCOLOR="#C0C0C0" SDVAL="0.791666666666666" SDNUM="1033;0;H:MM"><FONT FACE="Arial">19:00</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial">Dinner</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial">Dinner</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial">Dinner</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial">Freetime</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM BGCOLOR="#C0C0C0" SDVAL="0.812499999999999" SDNUM="1033;0;H:MM"><FONT FACE="Arial">19:30</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial">Dinner</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial">Dinner</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial">Dinner</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial">Dinner</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#00FFFF"><FONT FACE="Arial">Discussion</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial">Freetime</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial">Dinner</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial">Dinner</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial">Dinner</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM BGCOLOR="#C0C0C0" SDVAL="0.833333333333332" SDNUM="1033;0;H:MM"><FONT FACE="Arial">20:00</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FF9900"><FONT FACE="Arial">Presentation</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#00FFFF"><FONT FACE="Arial">Discussion</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#00FFFF"><FONT FACE="Arial">Discussion</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#00FFFF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM BGCOLOR="#C0C0C0" SDVAL="0.854166666666666" SDNUM="1033;0;H:MM"><FONT FACE="Arial">20:30</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FF9900"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#00FFFF"><FONT FACE="Arial">Discussion</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#00FFFF"><FONT FACE="Arial">Discussion</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#00FFFF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#00FFFF"><FONT FACE="Arial">Discussion</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#00FFFF"><FONT FACE="Arial">Discussion</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#00FFFF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial">Freetime</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FF9900"><FONT FACE="Arial">Presentation</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FF9900"><FONT FACE="Arial">Workshop</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FF9900"><FONT FACE="Arial">Workshop</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM BGCOLOR="#C0C0C0" SDVAL="0.874999999999999" SDNUM="1033;0;H:MM"><FONT FACE="Arial">21:00</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#00FFFF"><FONT FACE="Arial">Discussion</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#00FFFF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#00FFFF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial">Freetime</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#00FFFF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#00FFFF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#00FFFF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FF9900"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FF9900"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FF9900"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM BGCOLOR="#C0C0C0" SDVAL="0.895833333333332" SDNUM="1033;0;H:MM"><FONT FACE="Arial">21:30</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#00FFFF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial">Freetime</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial">Freetime</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial">Freetime</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial">Freetime</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#00FFFF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FF9900"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FF9900"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FF9900"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM BGCOLOR="#C0C0C0" SDVAL="0.916666666666666" SDNUM="1033;0;H:MM"><FONT FACE="Arial">22:00</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial">Freetime</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial">Freetime</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial">Freetime</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial">Freetime</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial">Freetime</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM BGCOLOR="#C0C0C0" SDVAL="0.937499999999999" SDNUM="1033;0;H:MM"><FONT FACE="Arial">22:30</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial">Saddle</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="5" SDNUM="1033;"><FONT FACE="Arial">5</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="9" SDNUM="1033;"><FONT FACE="Arial">9</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="9.5" SDNUM="1033;"><FONT FACE="Arial">9.5</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="9.5" SDNUM="1033;"><FONT FACE="Arial">9.5</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="10" SDNUM="1033;"><FONT FACE="Arial">10</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="9" SDNUM="1033;"><FONT FACE="Arial">9</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="10.5" SDNUM="1033;"><FONT FACE="Arial">10.5</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="9.5" SDNUM="1033;"><FONT FACE="Arial">9.5</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="6" SDNUM="1033;"><FONT FACE="Arial">6</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="2.5" SDNUM="1033;"><FONT FACE="Arial">2.5</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="8" SDNUM="1033;"><FONT FACE="Arial">8</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="0" SDNUM="1033;"><FONT FACE="Arial">0</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="9" SDNUM="1033;"><FONT FACE="Arial">9</FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial">Time (hrs)</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial">Overnight</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><FONT FACE="Arial">Woomera</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><FONT FACE="Arial">Arkaringa</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><FONT FACE="Arial">Simpson Desert</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><FONT FACE="Arial">Henbury</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><FONT FACE="Arial">Algebuckiner</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><FONT FACE="Arial">Cooper Creek</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><FONT FACE="Arial">Clifton Hills</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><FONT FACE="Arial">Merty Merty</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><FONT FACE="Arial">Arkaroola</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><FONT FACE="Arial">Arkaroola</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><FONT FACE="Arial">Arkaroola</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><FONT FACE="Arial">Arkaroola</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><FONT FACE="Arial">Adelaide</FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial">Key</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CCFFCC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial">Road time</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FFFF99"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial">Meals</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FF9900"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial">Formal expedition briefing, presentation or workshop</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#99CC00"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial">General accomodation or cleaning duties</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#CC99FF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial">Freetime - no formal activities</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#00FFFF"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial">General discussion time amongst team or with other parties</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=154 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM BGCOLOR="#FF99CC"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial">Contingency &quot;padding&quot; - currently unused time in itinerary</FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=107 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
	</TBODY>
</TABLE>
<!-- ************************************************************************** -->
<HR>
<A NAME="table1"><H1>Sheet 2: <EM>Team</EM></H1></A>
<TABLE FRAME=BELOW CELLSPACING=0 COLS=6 RULES=GROUPS BORDER=1>
	<COLGROUP><COL WIDTH=257><COL WIDTH=257><COL WIDTH=257><COL WIDTH=257><COL WIDTH=257><COL WIDTH=257></COLGROUP>
	<TBODY>
		<TR>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><B><FONT FACE="Arial">JNT-1 Team and Movements</FONT></B></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
		<TR>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><B><FONT FACE="Arial">Name</FONT></B></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><B><FONT FACE="Arial">Role</FONT></B></TD>
			<TD COLSPAN=2 WIDTH=514 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM BGCOLOR="#C0C0C0"><B><FONT FACE="Arial">INCOMING</FONT></B></TD>
			<TD COLSPAN=2 WIDTH=514 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM BGCOLOR="#808080"><B><FONT FACE="Arial" COLOR="#FFFFFF">OUTGOING</FONT></B></TD>
			</TR>
		<TR>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><B><FONT FACE="Arial"><BR></FONT></B></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><B><FONT FACE="Arial"><BR></FONT></B></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><B><FONT FACE="Arial">When</FONT></B></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><B><FONT FACE="Arial">How</FONT></B></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><B><FONT FACE="Arial">When</FONT></B></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><B><FONT FACE="Arial">How</FONT></B></TD>
		</TR>
	</TBODY>
	<TBODY>
		<TR>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial">Carol Stoker</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial">Technical Party</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
	</TBODY>
	<TBODY>
		<TR>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial">Larry Lemke</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial">Technical Party</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
	</TBODY>
	<TBODY>
		<TR>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial">Jonathan Clarke</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial">Expedition Leader</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
	</TBODY>
	<TBODY>
		<TR>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial">Graham Mann</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial">Technical Party</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="37191.4131944444" SDNUM="1033;0;DDD\ DD/MM/YY\ HH:MM"><FONT FACE="Arial">Sat 27/10/01 09:55</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><FONT FACE="Arial">Perth &gt; Adelaide</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="37205.5868055556" SDNUM="1033;0;DDD\ DD/MM/YY\ HH:MM"><FONT FACE="Arial">Sat 10/11/01 14:05</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><FONT FACE="Arial">Adelaide &gt; Perth</FONT></TD>
		</TR>
	</TBODY>
	<TBODY>
		<TR>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial">Vic Gostin</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDNUM="1033;0;DDD\ DD/MM/YY\ HH:MM"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDNUM="1033;0;DDD\ DD/MM/YY\ HH:MM"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
	</TBODY>
	<TBODY>
		<TR>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial">Malcolm Walter</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial">Technical Party</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDNUM="1033;0;DDD\ DD/MM/YY\ HH:MM"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDNUM="1033;0;DDD\ DD/MM/YY\ HH:MM"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
	</TBODY>
	<TBODY>
		<TR>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial">Matilda Thomas</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial">Technical Party</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDNUM="1033;0;DDD\ DD/MM/YY\ HH:MM"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDNUM="1033;0;DDD\ DD/MM/YY\ HH:MM"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
	</TBODY>
	<TBODY>
		<TR>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial">Jason Hoogland</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial">Technical Director</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="37190.3402777778" SDNUM="1033;0;DDD\ DD/MM/YY\ HH:MM"><FONT FACE="Arial">Fri 26/10/01 08:10</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><FONT FACE="Arial">Brisbane &gt; Adelaide</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="37191.8055555556" SDNUM="1033;0;DDD\ DD/MM/YY\ HH:MM"><FONT FACE="Arial">Sat 27/10/01 19:20</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><FONT FACE="Arial">Adelaide &gt; Brisbane</FONT></TD>
		</TR>
	</TBODY>
	<TBODY>
		<TR>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="37201.3854166667" SDNUM="1033;0;DDD\ DD/MM/YY\ HH:MM"><FONT FACE="Arial">Tue 06/11/01 09:15</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><FONT FACE="Arial">Brisbane &gt; Adelaide</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="37204.84375" SDNUM="1033;0;DDD\ DD/MM/YY\ HH:MM"><FONT FACE="Arial">Fri 09/11/01 20:15</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><FONT FACE="Arial">Adelaide &gt; Brisbane</FONT></TD>
		</TR>
	</TBODY>
	<TBODY>
		<TR>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDNUM="1033;0;DDD\ DD/MM/YY\ HH:MM"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDNUM="1033;0;DDD\ DD/MM/YY\ HH:MM"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
	</TBODY>
	<TBODY>
		<TR>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDNUM="1033;0;DDD\ DD/MM/YY\ HH:MM"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDNUM="1033;0;DDD\ DD/MM/YY\ HH:MM"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
	</TBODY>
	<TBODY>
		<TR>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial">John Deckert</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial">Support Party</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="37191.375" SDNUM="1033;0;DDD\ DD/MM/YY\ HH:MM"><FONT FACE="Arial">Sat 27/10/01 09:00</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><FONT FACE="Arial">4wd Vehicle Nhill, Victoria &gt; Adelaide</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="37204.6041666667" SDNUM="1033;0;DDD\ DD/MM/YY\ HH:MM"><FONT FACE="Arial">Fri 09/11/01 14:30</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><FONT FACE="Arial">4wd Vehicle Adelaide &gt; Nhill</FONT></TD>
		</TR>
	</TBODY>
	<TBODY>
		<TR>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial">Bev Deckert</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial">Support Party</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="37191.375" SDNUM="1033;0;DDD\ DD/MM/YY\ HH:MM"><FONT FACE="Arial">Sat 27/10/01 09:00</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><FONT FACE="Arial">4wd Vehicle Nhill, Victoria &gt; Adelaide</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDNUM="1033;0;DDD\ DD/MM/YY\ HH:MM"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><FONT FACE="Arial">4wd Vehicle Adelaide &gt; Nhill</FONT></TD>
		</TR>
	</TBODY>
	<TBODY>
		<TR>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial">Alan</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial">Support Party</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="37191.375" SDNUM="1033;0;DDD\ DD/MM/YY\ HH:MM"><FONT FACE="Arial">Sat 27/10/01 09:00</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><FONT FACE="Arial">4wd Vehicle Nhill, Victoria &gt; Adelaide</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDNUM="1033;0;DDD\ DD/MM/YY\ HH:MM"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><FONT FACE="Arial">4wd Vehicle Adelaide &gt; Nhill</FONT></TD>
		</TR>
	</TBODY>
	<TBODY>
		<TR>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial">Beryl</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial">Support Party</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="37191.375" SDNUM="1033;0;DDD\ DD/MM/YY\ HH:MM"><FONT FACE="Arial">Sat 27/10/01 09:00</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><FONT FACE="Arial">4wd Vehicle Nhill, Victoria &gt; Adelaide</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDNUM="1033;0;DDD\ DD/MM/YY\ HH:MM"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><FONT FACE="Arial">4wd Vehicle Adelaide &gt; Nhill</FONT></TD>
		</TR>
	</TBODY>
	<TBODY>
		<TR>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial">Bill</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial">Support Party</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="37191.375" SDNUM="1033;0;DDD\ DD/MM/YY\ HH:MM"><FONT FACE="Arial">Sat 27/10/01 09:00</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><FONT FACE="Arial">4wd Vehicle Nhill, Victoria &gt; Adelaide</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDNUM="1033;0;DDD\ DD/MM/YY\ HH:MM"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><FONT FACE="Arial">4wd Vehicle Adelaide &gt; Nhill</FONT></TD>
		</TR>
	</TBODY>
	<TBODY>
		<TR>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial">Rhonda</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial">Support Party</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="37191.375" SDNUM="1033;0;DDD\ DD/MM/YY\ HH:MM"><FONT FACE="Arial">Sat 27/10/01 09:00</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><FONT FACE="Arial">4wd Vehicle Nhill, Victoria &gt; Adelaide</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDNUM="1033;0;DDD\ DD/MM/YY\ HH:MM"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><FONT FACE="Arial">4wd Vehicle Adelaide &gt; Nhill</FONT></TD>
		</TR>
	</TBODY>
	<TBODY>
		<TR>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial">Rex</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial">Support Party</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="37191.375" SDNUM="1033;0;DDD\ DD/MM/YY\ HH:MM"><FONT FACE="Arial">Sat 27/10/01 09:00</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><FONT FACE="Arial">4wd Vehicle Nhill, Victoria &gt; Adelaide</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDNUM="1033;0;DDD\ DD/MM/YY\ HH:MM"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><FONT FACE="Arial">4wd Vehicle Adelaide &gt; Nhill</FONT></TD>
		</TR>
	</TBODY>
	<TBODY>
		<TR>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDNUM="1033;0;DDD\ DD/MM/YY\ HH:MM"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDNUM="1033;0;DDD\ DD/MM/YY\ HH:MM"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
	</TBODY>
	<TBODY>
		<TR>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial">Jennifer Laing</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial">Auxilliary Party</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="37190.5590277778" SDNUM="1033;0;DDD\ DD/MM/YY\ HH:MM"><FONT FACE="Arial">Fri 26/10/01 13:25</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM><FONT FACE="Arial">Melb &gt; Adelaide</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDVAL="37204.8576388889" SDNUM="1033;0;DDD\ DD/MM/YY\ HH:MM"><FONT FACE="Arial">Fri 09/11/01 20:35</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDNUM="1033;0;DDD\ DD/MM/YY\ HH:MM"><FONT FACE="Arial"> Adelaide &gt; Melb</FONT></TD>
		</TR>
	</TBODY>
	<TBODY>
		<TR>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial">Guy Murphy</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial">Auxilliary Party</FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDNUM="1033;0;DDD\ DD/MM/YY\ HH:MM"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDNUM="1033;0;DDD\ DD/MM/YY\ HH:MM"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
	</TBODY>
	<TBODY>
		<TR>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDNUM="1033;0;DDD\ DD/MM/YY\ HH:MM"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=CENTER VALIGN=BOTTOM SDNUM="1033;0;DDD\ DD/MM/YY\ HH:MM"><FONT FACE="Arial"><BR></FONT></TD>
			<TD WIDTH=257 HEIGHT=17 ALIGN=LEFT VALIGN=BOTTOM><FONT FACE="Arial"><BR></FONT></TD>
		</TR>
	</TBODY>
</TABLE>
<!-- ************************************************************************** -->
</BODY>

</HTML>
