<?php

/**
 * Implementation of hook_menu().
 */
function select_province_menu() {
  $items = array();
  $items['ajax/get-provinces'] = array(
    'access callback' => TRUE,
    'page callback' => 'select_province_get',
    'page arguments' => array(2),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Adds JavaScript to the form that replaces province autocomplete fields with selectors.
 *
 * @param array $form
 * @param array $form_state
 */
function select_province_form_alter(&$form, &$form_state) {
  // Add the JS:
  drupal_add_js(drupal_get_path('module', 'select_province') . '/select_province.js');
}

/**
 * Get the provices/states for this country and send to client as JSON.
 *
 * @param string $country_code
 */
function select_province_get($country_code) {
  echo json_encode(array_merge(array('' => 'Please select'), location_get_provinces($country_code)));
  exit;
}
