<?php

global $php_root_path ;	
global $privilege_root_path ;

require_once ( "$php_root_path/".$privilege_root_path."/phase/phasebase.inc" ) ;
require_once ( "$php_root_path/".$privilege_root_path."/phase/phase1.inc" ) ;
require_once ( "$php_root_path/".$privilege_root_path."/phase/phase2.inc" ) ;
require_once ( "$php_root_path/".$privilege_root_path."/phase/phase3.inc" ) ;
require_once ( "$php_root_path/".$privilege_root_path."/phase/phase4.inc" ) ;
	
?>